<a href="https://colab.research.google.com/github/dmitrijrazdrokin90/Algoritms/blob/master/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D1%8B_%D1%81%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import time


row = np.random.randint(0, 1000, 100)


def bubble_sort(array):
    for i in range(len(array) - 1):
        for j in range(len(array) - i - 1):
            if array[j] > array[j + 1]:
                array[j], array[j + 1] = array[j + 1], array[j]
    return array


print(row)
bubble_sort(row)
print(row)
print(time.process_time())

[930 558 893 730  19 399 283  53 512 724 630 277 117 825 997 219 582 569
 463  15 914 729 822 264 120  17 623 450 115 851  53 880 654 475  34 609
 155 349 924 646 644 548 596 989 743 168 436 908 439 361 814 562 487 430
 974 791 987 987 783 544 654 856 902  94 208 848 473 898 499 115 619  18
 311 812 160 589 358 804 453 581 829 827 218 744  67 623 189 335 679  41
 868 722 177 850 859 765  12 852 952 415]
[ 12  15  17  18  19  34  41  53  53  67  94 115 115 117 120 155 160 168
 177 189 208 218 219 264 277 283 311 335 349 358 361 399 415 430 436 439
 450 453 463 473 475 487 499 512 544 548 558 562 569 581 582 589 596 609
 619 623 623 630 644 646 654 654 679 722 724 729 730 743 744 765 783 791
 804 812 814 822 825 827 829 848 850 851 852 856 859 868 880 893 898 902
 908 914 924 930 952 974 987 987 989 997]
1.509115536


In [2]:
import numpy as np
import time


row = np.random.randint(0, 1000, 100)


def insertion_sort(array):
    for i in range(len(array)):
        j = i - 1
        key = array[i]
        while array[j] > key and j >= 0:
            array[j + 1] = array[j]
            j -= 1
        array[j + 1] = key
    return array


print(row)
insertion_sort(row)
print(row)
print(time.process_time())

[745 162 721 734  72 672  76 522 228 677 584 380  13 259 391 133 993 974
 334 804 164 606 139 873 971 173 969 971 347 106 969 445 610 221 816 564
 161 877 946 263 389 757 896  55 149 712 858 715 728 899 959  54  41 616
  56 302  71 995 916 312 561  38 464 552 970 371 231 520  93 617 472 495
 449 407 294 180 545 385 866 187 108 643  30 101  53 515 637 575 594 708
 193 373 473 166 442 617 916 529 761 780]
[ 13  30  38  41  53  54  55  56  71  72  76  93 101 106 108 133 139 149
 161 162 164 166 173 180 187 193 221 228 231 259 263 294 302 312 334 347
 371 373 380 385 389 391 407 442 445 449 464 472 473 495 515 520 522 529
 545 552 561 564 575 584 594 606 610 616 617 617 637 643 672 677 708 712
 715 721 728 734 745 757 761 780 804 816 858 866 873 877 896 899 916 916
 946 959 969 969 970 971 971 974 993 995]
1.535937557


In [3]:
import random as rd


def merge_sort(array):
    if len(array) > 1:
        mid = len(array) // 2
        L = array[:mid]
        R = array[mid:]
        merge_sort(L)
        merge_sort(R)
        i = j = k = 0
        while i < len(L) and j < len(R):
            if L[i] < R[j]:
                array[k] = L[i]
                i += 1
            else:
                array[k] = R[j]
                j += 1
            k += 1
        while i < len(L):
            array[k] = L[i]
            i += 1
            k += 1
        while j < len(R):
            array[k] = R[j]
            j += 1
            k += 1
    return array


def array_init(n):
    array = []
    for i in range(n):
        array.append(rd.randint(0, 100))
    return array


arr = array_init(100)
print("Given array is: \n", arr)
merge_sort(arr)
print("Sorted array is: \n", arr)

Given array is: 
 [93, 75, 71, 48, 67, 40, 39, 58, 43, 64, 54, 88, 28, 28, 67, 99, 74, 1, 5, 63, 48, 28, 74, 68, 63, 32, 27, 78, 31, 97, 10, 32, 6, 14, 24, 50, 39, 31, 63, 14, 99, 83, 80, 100, 9, 73, 85, 10, 80, 8, 77, 91, 9, 58, 22, 32, 55, 35, 98, 70, 66, 4, 28, 41, 30, 58, 96, 64, 21, 56, 1, 28, 58, 41, 78, 43, 92, 36, 31, 46, 29, 46, 61, 2, 38, 40, 44, 62, 23, 38, 80, 36, 65, 22, 21, 27, 97, 20, 51, 66]
Sorted array is: 
 [1, 1, 2, 4, 5, 6, 8, 9, 9, 10, 10, 14, 14, 20, 21, 21, 22, 22, 23, 24, 27, 27, 28, 28, 28, 28, 28, 29, 30, 31, 31, 31, 32, 32, 32, 35, 36, 36, 38, 38, 39, 39, 40, 40, 41, 41, 43, 43, 44, 46, 46, 48, 48, 50, 51, 54, 55, 56, 58, 58, 58, 58, 61, 62, 63, 63, 63, 64, 64, 65, 66, 66, 67, 67, 68, 70, 71, 73, 74, 74, 75, 77, 78, 78, 80, 80, 80, 83, 85, 88, 91, 92, 93, 96, 97, 97, 98, 99, 99, 100]


In [4]:
import numpy as np
import time


row = np.random.randint(0, 1000, 100)


def selection_sort(array):
    for i in range(len(array) - 1):
        m = i
        j = i + 1
        while j < len(array):
            if array[j] < array[m]:
                m = j
            j += 1
        array[i], array[m] = array[m], array[i]
    return array


print(row)
selection_sort(row)
print(row)
print(time.process_time())

[316 797 674 945 919 755 420 210 285 623 538 960  62 418 457 760 130 370
 433  51 624 808 440 858 156  70 388 223 800 264 584 992 207 726 790  39
 716 447 513 106 425 432 640 668 600 542 353 933 878 511 439 703 735 677
 577  97 485 933 319 234 704 321 630 396 225 958 252 984 410 133 141 198
 923 348 100 229 936 635  61 300 673 499 612 632 713 299  87 261  63 212
 842 245 262  79  26 988  82 177 191 154]
[ 26  39  51  61  62  63  70  79  82  87  97 100 106 130 133 141 154 156
 177 191 198 207 210 212 223 225 229 234 245 252 261 262 264 285 299 300
 316 319 321 348 353 370 388 396 410 418 420 425 432 433 439 440 447 457
 485 499 511 513 538 542 577 584 600 612 623 624 630 632 635 640 668 673
 674 677 703 704 713 716 726 735 755 760 790 797 800 808 842 858 878 919
 923 933 933 936 945 958 960 984 988 992]
1.6320176690000001


In [5]:
import numpy as np
import time


row = np.random.randint(0, 100, 10)


def shaker_sort(array):
    up = range(len(array) - 1)
    while True:
        for indices in (up, reversed(up)):
            swapped = False
            for i in indices:
                if array[i] > array[i + 1]:
                    array[i], array[i + 1] = array[i + 1], array[i]
                    swapped = True
        if not swapped:
            return array


print(row)
shaker_sort(row)
print(row)
print(time.process_time())

[65 77 39 86 24 39 58 21 67 40]
[21 24 39 39 40 58 65 67 77 86]
1.673233286


In [6]:
import numpy as np
import time


row = np.random.randint(0, 100, 10)


def shell_sort(array):
    n = len(array)
    gap = n // 2
    while gap > 0:
        for i in range(gap, n):
            temp = array[i]
            j = i
            while j >= gap and array[j - gap] > temp:
                array[j] = array[j - gap]
                j -= gap
            array[j] = temp
        gap //= 2
    return array


print(row)
shell_sort(row)
print(row)
print(time.process_time())

[29 76  2 16 48 55  4 90 70 97]
[ 2  4 16 29 48 55 70 76 90 97]
2.195664993


In [7]:
import random as rd


def partition(array, low, high):
    i = low - 1
    pivot = array[high]
    for j in range(low, high):
        if array[j] < pivot:
            i += 1
            array[i], array[j] = array[j], array[i]
    array[i + 1], array[high] = array[high], array[i + 1]
    return i + 1


def quick_sort_legacy(array, low, high):
    if low < high:
        part_index = partition(array, low, high)
        quick_sort_legacy(array, low, part_index - 1)
        quick_sort_legacy(array, part_index + 1, high)
    return array


def quick_sort(array):
    quick_sort_legacy(array, 0, len(array) - 1)


def array_init(n):
    array = []
    for i in range(n):
        array.append(rd.randint(0, 100))
    return array


arr = array_init(100)
print("Unsorted array is: \n", arr)
quick_sort(arr)
print("Sorted array is: \n", arr)

Unsorted array is: 
 [7, 84, 46, 12, 64, 52, 94, 59, 45, 93, 95, 51, 23, 54, 43, 60, 19, 57, 11, 70, 70, 45, 96, 47, 13, 22, 55, 17, 94, 61, 91, 64, 97, 59, 19, 86, 90, 20, 98, 14, 21, 73, 92, 30, 65, 90, 18, 96, 4, 25, 42, 21, 35, 9, 34, 90, 11, 11, 38, 21, 42, 49, 33, 15, 12, 15, 15, 66, 72, 52, 4, 61, 76, 61, 89, 8, 38, 14, 91, 5, 35, 6, 35, 80, 37, 22, 49, 50, 8, 100, 75, 11, 70, 28, 24, 17, 3, 66, 49, 64]
Sorted array is: 
 [3, 4, 4, 5, 6, 7, 8, 8, 9, 11, 11, 11, 11, 12, 12, 13, 14, 14, 15, 15, 15, 17, 17, 18, 19, 19, 20, 21, 21, 21, 22, 22, 23, 24, 25, 28, 30, 33, 34, 35, 35, 35, 37, 38, 38, 42, 42, 43, 45, 45, 46, 47, 49, 49, 49, 50, 51, 52, 52, 54, 55, 57, 59, 59, 60, 61, 61, 61, 64, 64, 64, 65, 66, 66, 70, 70, 70, 72, 73, 75, 76, 80, 84, 86, 89, 90, 90, 90, 91, 91, 92, 93, 94, 94, 95, 96, 96, 97, 98, 100]


In [8]:
import numpy as np
import time


row = np.random.randint(0, 100, 10)


def gnome_sort(array):
    i, size = 1, len(array)
    while i < size:
        if array[i - 1] <= array[i]:
            i += 1
        else:
            array[i - 1], array[i] = array[i], array[i - 1]
            if i > 1:
                i -= 1
    return array


print(row)
gnome_sort(row)
print(row)
print(time.process_time())

[23 89 37 49  8 60 39 60 97 49]
[ 8 23 37 39 49 49 60 60 89 97]
2.275197096


In [9]:
import numpy as np
import time


row = np.random.randint(0, 100, 10)


def opt_gnome_sort(array):
    i, j, size = 1, 2, len(array)
    while i < size:
        if array[i - 1] <= array[i]:
            i, j = j, j + 1
        else:
            array[i - 1], array[i] = array[i], array[i - 1]
            i -= 1
            if i == 0:
                i, j = j, j + 1
    return array


print(row)
opt_gnome_sort(row)
print(row)
print(time.process_time())

[58 76 84 31 47 19 45 52 71 72]
[19 31 45 47 52 58 71 72 76 84]
2.309808428
